### PR TITLE
Create sq_AL - Albanian language

### PR DESCRIPTION
**Pull request by olsigjeci**
Hello and thank you for this wonderful gem. Since I am Albanian I am submitting the Albanian version of the consent banner.

### CODE REVIEW

**Comment by gabskoro** [comment]
Tnx, can you also please add it to the Readme? :)

**Comment by olsigjeci** [comment]
added Albanian in readme

**Comment by gabskoro** [comment]
Tnx 👍

**Comment by olsigjeci** [comment]
thanks

**Comment by olsigjeci** [comment]
sorry had to rename the file with yml extension!

**Comment by gabskoro** [comment]
Oh, didn't see it, I'll fix it 👍

**Pull request merged**
