### PR TITLE
Make it work with Turbolinks

### PR DESCRIPTION
**Pull request by haffla**
I know there has been some discussion about this gem and Turbolinks, but I never understood the problem. This PR makes it work with Turbolinks.

### CODE REVIEW

**Comment by mapreal19** [comment]
I guess we should updating the readme too?

**Comment by haffla** [comment]
@mapreal19 you meaning removing the "Turbolinks NOT supported" section. Yes, I totally forgot. Will do.

**Comment by mapreal19** [comment]
@haffla yeah 👍

**Comment by gildesmarais** [comment]
Thanks @haffla - this is exactly what I've been looking for. 🎉

Is there anything preventing the merge and a version bump of this gem?

**Comment by gabskoro** [comment]
Hey guys, sorry for taking so long :) 

Actually adding support for Turbolinks wouldn't break anything, because around two years ago [we removed](https://github.com/infinum/cookies_eu/commit/a037b41fd7af7194a59b508b4dfd1a68c0301e2f) jQuery completely, so it also never worked with an older version of Turbolinks (`jquery-turbolinks` listens for jquery's ready event)

I will also clean up the code a little bit later (not sure why I added the load event in the first place)

Tnx @haffla !

**Pull request merged**
